name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: coe-platform-engineering-rg
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build Next.js app
      run: npm run build

    - name: Create deployment package
      run: |
        cp package.json .next/standalone/
        cp -r .next/static .next/standalone/.next/
        if [ -d "public" ]; then cp -r public .next/standalone/; fi
        cd .next/standalone
        zip -r ../../deployment.zip .

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-app
        path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment:
      name: 'production'

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: nextjs-app

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

    - name: Extract deployment info from catalog
      id: get-config
      run: |
        # Extract Azure Web App name from catalog-info.yaml
        WEBAPP_NAME=$(grep -oP 'AZURE_WEBAPP_NAME:\s*\K[^ ]+' catalog-info.yaml || echo "")
        if [ -z "$WEBAPP_NAME" ]; then
          echo "Error: AZURE_WEBAPP_NAME not found in catalog-info.yaml"
          exit 1
        fi
        echo "webapp_name=$WEBAPP_NAME" >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp deployment source config-zip \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name ${{ steps.get-config.outputs.webapp_name }} \
          --src deployment.zip
      continue-on-error: true

    - name: Logout from Azure
      run: az logout
